import '@testing-library/jest-dom';

// Mock window.api for Electron IPC
window.api = {
  agents: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  providers: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  models: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  accounts: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  apiKeys: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  projects: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  notes: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  tags: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  settings: {
    get: vi.fn(),
    set: vi.fn(),
    getAll: vi.fn(),
    delete: vi.fn(),
  },
  db: {
    backup: vi.fn(),
    restore: vi.fn(),
    export: vi.fn(),
    import: vi.fn(),
    listBackups: vi.fn(),
    deleteBackup: vi.fn(),
  },
  window: {
    minimize: vi.fn(),
    maximize: vi.fn(),
    close: vi.fn(),
  },
  app: {
    version: vi.fn(),
    path: vi.fn(),
  },
  activity: {
    list: vi.fn(),
    getByEntity: vi.fn(),
    getRecent: vi.fn(),
    getStats: vi.fn(),
  },
  analytics: {
    usageOverTime: vi.fn(),
    costOverTime: vi.fn(),
    costByProvider: vi.fn(),
    costByModel: vi.fn(),
    costByProject: vi.fn(),
    usageByModel: vi.fn(),
    tokenDistribution: vi.fn(),
  },
  quotas: {
    list: vi.fn(),
    get: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    active: vi.fn(),
    upcomingResets: vi.fn(),
    expired: vi.fn(),
    updateUsage: vi.fn(),
    incrementUsage: vi.fn(),
    resetUsage: vi.fn(),
  },
  notifications: {
    list: vi.fn(),
    getUnread: vi.fn(),
    unreadCount: vi.fn(),
    markAsRead: vi.fn(),
    markAllAsRead: vi.fn(),
    create: vi.fn(),
    checkQuotas: vi.fn(),
    deleteOlderThan: vi.fn(),
  },
  favorites: {
    list: vi.fn(),
    get: vi.fn(),
    toggle: vi.fn(),
    isFavorited: vi.fn(),
    findByType: vi.fn(),
    count: vi.fn(),
    delete: vi.fn(),
  },
  templates: {
    list: vi.fn(),
    get: vi.fn(),
    getConfig: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    findByType: vi.fn(),
    duplicate: vi.fn(),
  },
};
